# WhatATheme
markdown: kramdown
site-keywords: HifiCouch, Audiophile

title: HiFi Couchsurfing
email: gf@zerohat.net
description: >- # this means to ignore newlines until "baseurl:"
  Meet audiophiles and music enthusiast all over the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hificouch.world" # the base hostname & protocol for your site, e.g. http://example.com

author-name: 'Geri F.'
author-image: "/assets/images/author.jpg"

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
theme: minima
plugins:
  - jekyll-leaflet
  - jekyll-mermaid
  - jekyll-paginate
  - jekyll-admin
  - jekyll-feed
  - jemoji



site-image: "/assets/images/df_logo.jpg"
heroimage: "/assets/images/df_logo.jpg"

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
