# WhatATheme
markdown: kramdown
site-keywords: HifiCouch, Audiophile, DIY

title: HiFi Setups - Couchsurfing
description: >- # this means to ignore newlines until "baseurl:"
  Meet audiophiles and music enthusiasts all over the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hificouch.world" # the base hostname & protocol for your site, e.g. http://example.com

author-name: "Geri F."
author-image: "/assets/images/author.jpg"
author-url: "https://www.linkedin.com/in/%F0%9F%9A%80-gerald-fehringer-376b84142/"

site-image: "/assets/images/gerihifi-banner.png"
heroimage: "/assets/images/gerihifi-banner.png"

email: gf@zerohat.net
github_username: geraldfehringer

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
theme: minima
plugins:
#  - jekyll-leaflet
  - jekyll-mermaid
  - jekyll-paginate
  #- jekyll-admin
  - jekyll-feed
  - jemoji
  - jekyll-toc
  - jekyll-minimagick
  - jekyll-thumbnail

# TOC Settings
toc:
 min_level: 1
 max_level: 2
 list_class: toc
 list_class: toc__list
 sublist_class: toc__sublist

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
