name: Parse CSV and validate fields

on:
  workflow_dispatch:
  #schedule:
    # Runs "At 03:00 on every day"
  #  - cron: '0 3 * * *'

env:
  HIFI_STG_SAS: ${{secrets.HIFI_STG_SAS_TOKEN}}

jobs:
  build:
    name: Trigger CSV Fix for HifiSetups
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install-with-cpanm
        uses: perl-actions/install-with-cpanm@stable
        with:
          sudo: false
      - name: Fix CSV dates and more
        run: |
          echo "Get Storage Blob CSV file"
          if [ -f "assets/csv/hifisetups_tmp.csv" ]; then
            rm -f assets/csv/hifisetups_tmp.csv
          fi
          sudo cpanm Text::CSV
          sudo cpanm DateTime::Format::Excel
          azcopy copy "${{ env.HIFI_STG_SAS }}" assets/csv/
          echo "### cut 2 columns"
          cat assets/csv/hifisetups_tmp.csv | cut -d"," -f2-20 >assets/csv/hifisetups_tmp2.csv
          echo "### cut header row"
          sed '1,1d' assets/csv/hifisetups_tmp2.csv > assets/csv/hifisetups_tmp3.csv
          echo "### fix excel date"
          perl fixexceldate.pl
          echo "### add header"
          sed -i 's/"//g' hifisetups_fix.csv
          head -1 assets/csv/hifisetups_tmp2.csv > assets/csv/hifisetups.csv
          cat hifisetups_fix.csv >> hifisetups.csv
          git config --global user.name "geraldfehringer"
          git add assets/csv/hifisetups.csv
          git commit -m 'new hifisetups.csv added'
          pit push origin main
          

