name: Parse CSV and validate fields

on:
  workflow_dispatch:
  schedule:
    # Runs "At 03:00 on every day"
    - cron: '13 4 * * *'

env:
  HIFI_STG_SAS: ${{secrets.HIFI_STG_SAS_TOKEN}}

jobs:
  build:
    name: Trigger CSV Fix for HifiSetups
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      #- name: Install-with-cpanm
      #  uses: perl-actions/install-with-cpanm@stable
      #  with:
      #    sudo: true
      #    install: |
      #      Text::CSV
      #      DateTime::Format::Excel
      - name: Fix CSV dates and more
        run: |
          # sudo cpanm Text::CSV
          # sudo cpanm DateTime::Format::Excel
          echo "Get Storage Blob CSV file"
          mkdir assets/csv/
          azcopy copy "${{ env.HIFI_STG_SAS }}" assets/csv/
          ls -la assets/csv/
          exit 0
          if [ -f "assets/csv/hifisetups_tmp.csv" ]; then
           echo "### cut 2 columns"
           cat assets/csv/hifisetups_tmp.csv | cut -d"," -f3-20 >assets/csv/hifisetups_tmp2.csv
           echo "### cut header row"
           sed '1,1d' assets/csv/hifisetups_tmp2.csv > assets/csv/hifisetups_tmp3.csv
           echo "### fix excel date"
           perl fixexceldate.pl
           echo "### add header to new hifisetups.csv"
           sed -i 's/"//g' hifisetups_fix.csv
           echo "### create NEW assets/csv/hifisetups.csv"
           touch assets/csv/hifisetups.csv
           head -1 assets/csv/hifisetups_tmp2.csv > assets/csv/hifisetups.csv
           echo "### add data from csv to new hifisetups.csv"
           cat hifisetups_fix.csv >> assets/csv/hifisetups.csv
           cat assets/csv/hifisetups.csv
           echo "FIXSTATUS=1" >> "$GITHUB_ENV"
           git config --global user.name "geraldfehringer"
           git config --global user.email "gf@zerohat.net"
           git add assets/csv/hifisetups.csv
           git commit -m 'new hifisetups.csv added'
          fi
      - name: Push changes
        if: env.FIXSTATUS == '1'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
