name: Parse CSV and validate fields

on:
  workflow_dispatch:
  schedule:
    # Runs "At 03:00 on every day"
    - cron: '13 4 * * *'

env:
  HIFI_STG_SAS: ${{secrets.HIFI_STG_SAS_TOKEN}}

jobs:
  build:
    name: Trigger CSV Fix for HifiSetups
    runs-on: ubuntu-latest
    steps:
      - name: Install-with-cpanm
        uses: perl-actions/install-with-cpanm@stable
        with:
          sudo: true
          install: |
            Text::CSV
            DateTime::Format::Excel
      - uses: actions/checkout@v4
      - run: |
          echo "Get Storage Blob CSV file"
          if [ ! -d "assets/csv/" ]; then
            mkdir -p assets/csv/
          fi
          azcopy copy "${{ env.HIFI_STG_SAS }}" assets/csv/
          echo "### new file:hifisetups_tmp.csv"
          ls -la assets/csv/
          git config --global user.name "geraldfehringer"
          git config --global user.email "gf@zerohat.net"
          if [ -f "assets/csv/hifisetups_tmp.csv" ]; then
           echo "### cut 2 columns"
           cat assets/csv/hifisetups_tmp.csv | cut -d"," -f3-18 >assets/csv/hifisetups_tmp2.csv
           echo "### cut header row"
           sed '1,1d' assets/csv/hifisetups_tmp2.csv > assets/csv/hifisetups_tmp3.csv
           echo "### fix excel date"
           perl fixexceldate.pl
           echo "### add header to new hifisetups.csv"
           sed -i 's/"//g' hifisetups_fix.csv
           echo "### create NEW assets/csv/hifisetups.csv"
           if [ -f "assets/csv/hifisetups.csv" ] ; then
             echo "### DELETE old assets/csv/hifisetups.csv"
             git rm assets/csv/hifisetups.csv
             git commit -m 'delete old hifisetups.csv'
             git push
             git pull
           fi
           touch assets/csv/hifisetups.csv
           echo "### hifisetups.csv touched:"
           ls -la assets/csv/
           head -1 assets/csv/hifisetups_tmp2.csv > assets/csv/hifisetups.csv
           echo "### add data from csv to new hifisetups.csv"
           cat hifisetups_fix.csv >> assets/csv/hifisetups.csv
           rm -f hifisetups_fix.csv
           rm -f assets/csv/hifisetups_tmp.csv
           rm -f assets/csv/hifisetups_tmp3.csv
           rm -f assets/csv/hifisetups_tmp2.csv
           echo "##new CVS: "
           ls -la assets/csv/hifisetups.csv
           git add assets/csv/hifisetups.csv
           git commit -m 'new hifisetups.csv added'
           git push -f
          fi
